language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - TARGET_API_LEVEL=28
    - MIN_API_LEVEL=21
    - BUILD_TOOLS_VERSION=28.0.3
    - ADB_INSTALL_TIMEOUT=30
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - QEMU_AUDIO_DRV=none
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$TARGET_API_LEVEL
    - android-$MIN_API_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-25

licenses:
  - android-sdk-license-.+

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_script:
  - openssl aes-256-cbc -K $encrypted_92880d98bad7_key -iv $encrypted_92880d98bad7_iv -in google-services.json.enc -out app/google-services.json -d
  - chmod +x gradlew

script:
  - echo no | android create avd --force -n test -t "android-"$TARGET_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - ./gradlew test
  - ./gradlew connectedAndroidTest